name: Automatic testing (tobii)

on: [push]

jobs:
  Testing:

    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Checkout externals
        run: |
          git submodule init
          git submodule update

      - name: Install pyWinhook
        run: pip install pyWinhook==1.6.1

      - name: Install PsychoPy
        run: pip install psychopy==3.2.3

      - name: Install Pyglet
        run: pip install pyglet==1.3.2

      - name: Install Tobii SDK
        run: pip install tobii_research

      - name: Install Pytest
        run: pip install pytest

      - name: Run tests
        run: |
          cd test
          pytest